# Generated by Django 5.1.2 on 2025-12-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_manuscript_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='affiliations',
            field=models.TextField(blank=True, help_text='Author affiliations'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='co_authors',
            field=models.CharField(blank=True, help_text='Names of co-authors, separated by commas', max_length=500),
        ),
        migrations.AddField(
            model_name='review',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
