# Generated by Django 5.1.2 on 2025-12-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=20),
        ),
    ]
