# Generated by Django 5.1.2 on 2025-12-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_manuscript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Has the publication fee been paid?'),
        ),
    ]
