# Generated by Django 5.1.2 on 2025-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_manuscript_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
