# Generated by Django 5.1.2 on 2025-12-31 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('news', 'News'), ('call_for_papers', 'Call for Papers'), ('maintenance', 'Maintenance'), ('general', 'General')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
