# Generated by Django 6.0 on 2026-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, help_text='Format: XXXX-XXXX-XXXX-XXXX', max_length=19, null=True),
        ),
    ]
