# Generated by Django 5.1.2 on 2026-03-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_user_orcid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='reviewer',
        ),
    ]
