# Generated by Django 4.2.7 on 2026-03-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0009_user_orcid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="The URL component for this page (e.g., 'about')",
                        unique=True,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        default="journal/page.html",
                        help_text="The template to use for rendering this page",
                        max_length=100,
                    ),
                ),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content",
                    models.TextField(help_text="HTML content for this section"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="page_sections/"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Order of display")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="journal.page",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
