# Generated by Django 6.0 on 2026-04-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0009_user_orcid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the page",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL handle for the page", unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        help_text="Unique key identifier for the section (e.g. 'hero_title')",
                        max_length=100,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("html", "Rich HTML Content"),
                            ("image", "Image Upload"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True,
                        help_text="Used for text and HTML content",
                        null=True,
                    ),
                ),
                (
                    "image_content",
                    models.ImageField(
                        blank=True,
                        help_text="Upload images here",
                        null=True,
                        upload_to="page_images/",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which sections appear in Admin"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="journal.page",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("page", "section_key")},
            },
        ),
    ]
