# Generated by Django 4.2.7 on 2026-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0010_page_pagesection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagesection",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Order of display. Leave as 0 to append to the end.",
            ),
        ),
    ]
