# Generated by Django 6.0 on 2026-04-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0010_page_pagesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesection",
            name="external_link",
            field=models.URLField(
                blank=True, help_text="External link for images/banners", null=True
            ),
        ),
        migrations.AddField(
            model_name="pagesection",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="Link to Vimeo or YouTube video", null=True
            ),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Plain Text"),
                    ("html", "Rich HTML Content"),
                    ("image", "Image Upload"),
                    ("video", "Video Embed"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
