# Generated by Django 4.2.7 on 2026-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0011_alter_pagesection_options_alter_pagesection_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagesection",
            options={"ordering": ["location", "order", "id"]},
        ),
        migrations.AddField(
            model_name="pagesection",
            name="location",
            field=models.CharField(
                choices=[("main", "Main Content"), ("sidebar", "Sidebar")],
                default="main",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Order within chosen location. Leave as 0 to append.",
            ),
        ),
    ]
