# Generated by Django 4.2.7 on 2026-03-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0010_remove_manuscript_reviewer"),
        ("journal", "0012_alter_pagesection_options_pagesection_location_and_more"),
    ]

    operations = []
