# Generated by Django 5.1.2 on 2026-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_merge_20260315_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible_to_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revisions_required', 'Revisions Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=20),
        ),
    ]
