# Generated by Django 5.1.2 on 2026-03-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_review_is_visible_to_author_alter_manuscript_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('needs_revision', 'Needs Revision'), ('revision_submitted', 'Revision Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=20),
        ),
    ]
