# Generated by Django 5.1.2 on 2026-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_manuscript_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
