# Generated by Django 5.1.2 on 2026-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_review_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='response_to_reviewers',
            field=models.TextField(blank=True, help_text="Author's response to reviewer concerns"),
        ),
        migrations.AddField(
            model_name='review',
            name='declined_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='invitation_status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='assigned', max_length=20),
        ),
    ]
