# Generated by Django 5.1.2 on 2026-03-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_manuscript_response_to_reviewers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_responses', to='journal.manuscript')),
            ],
            options={
                'ordering': ['-round'],
            },
        ),
    ]
