# Generated by Django 5.1.2 on 2026-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_authorresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='current_round',
            field=models.PositiveIntegerField(default=1, help_text='The current version/cycle identifier'),
        ),
    ]
