# Generated by Django 6.0 on 2026-06-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_alter_announcement_content'),
        ('journal', '0019_manuscript_current_round'),
    ]

    operations = [
    ]
