# Generated by Django 4.2.7 on 2026-03-28 20:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0019_manuscript_current_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard (Rich Text)"),
                    ("VIDEO", "Vimeo Video"),
                    ("ORGANOGRAM", "Organogram (Leadership List)"),
                    ("GRID", "2-Column Grid"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pagesection",
            name="vimeo_url",
            field=models.URLField(
                blank=True,
                help_text="Paste the Vimeo video URL here (e.g., https://vimeo.com/12345)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="content",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Text content for standard or grid sections",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="OrganogramItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(help_text="e.g., 01, 02", max_length=10)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "color_code",
                    models.CharField(
                        default="#00529B",
                        help_text="Hex color code (e.g., #00529B)",
                        max_length=7,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organogram_items",
                        to="journal.pagesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "number"],
            },
        ),
    ]
