# Generated by Django 4.2.1 on 2026-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_merge_20260607_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
