# Generated by Django 4.2.1 on 2026-04-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0011_pagesection_external_link_pagesection_video_url_and_more"),
        ("journal", "0020_pagesection_section_type_pagesection_vimeo_url_and_more"),
    ]

    operations = []
