# Generated by Django 4.2.1 on 2026-05-02 11:25

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("mission_text", models.TextField()),
                ("vision_text", models.TextField()),
                ("objective_1", models.TextField()),
                ("objective_2", models.TextField()),
                ("objective_3", models.TextField()),
                ("objective_4", models.TextField()),
            ],
            options={
                "verbose_name": "About Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AimScopePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("aim_text", models.TextField()),
                ("scope_intro", models.TextField()),
                (
                    "scope_col1",
                    models.TextField(
                        help_text="Newline-separated scope items (left column)"
                    ),
                ),
                (
                    "scope_col2",
                    models.TextField(
                        help_text="Newline-separated scope items (right column)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aim & Scope Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ArchivingPolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archiving_text", models.TextField()),
                ("repository_text", models.TextField()),
            ],
            options={
                "verbose_name": "Archiving Policy Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AuthorGuidelinesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_journal_text", models.TextField()),
                ("open_access_policy_text", models.TextField()),
                ("publication_schedule_text", models.TextField()),
                ("editorial_policy_text", models.TextField()),
                ("general_requirements_text", models.TextField()),
                ("manuscript_preparation_text", models.TextField()),
                ("cover_letter_text", models.TextField()),
                ("title_page_text", models.TextField()),
                ("abstract_text", models.TextField()),
                ("keywords_text", models.TextField()),
                ("introduction_text", models.TextField()),
                ("materials_methods_text", models.TextField()),
                ("result_discussion_text", models.TextField()),
                ("results_text", models.TextField()),
                ("discussion_text", models.TextField()),
                ("conclusion_text", models.TextField()),
                ("acknowledgements_text", models.TextField()),
                ("conflicts_text", models.TextField()),
                ("references_intro_text", models.TextField()),
                ("submission_text", models.TextField()),
                ("assessment_text", models.TextField()),
                ("publication_fees_text", models.TextField()),
                (
                    "checklist_items",
                    models.TextField(help_text="Newline-separated checklist items"),
                ),
            ],
            options={
                "verbose_name": "Author Guidelines Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office_journal_name", models.CharField(max_length=200)),
                ("office_department", models.CharField(max_length=200)),
                ("office_institution", models.CharField(max_length=200)),
                ("office_address_line1", models.CharField(max_length=200)),
                ("office_address_line2", models.CharField(max_length=200)),
                ("principal_name", models.CharField(max_length=200)),
                ("principal_role", models.CharField(max_length=200)),
                ("principal_email", models.CharField(max_length=200)),
                ("principal_phone", models.CharField(max_length=50)),
                ("support_name", models.CharField(max_length=200)),
                ("support_role", models.CharField(max_length=200)),
                ("support_email", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Contact Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EditorialPolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
            ],
            options={
                "verbose_name": "Editorial Policy Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EditorialTeamPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("managing_director_description", models.TextField()),
                ("editorial_assistant_description", models.TextField()),
                ("section_editors_description", models.TextField()),
                ("editorial_board_description", models.TextField()),
            ],
            options={
                "verbose_name": "Editorial Team Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EthicsMalpracticePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                (
                    "editors_responsibilities",
                    models.TextField(help_text="Newline-separated items"),
                ),
                ("reviewers_intro_text", models.TextField()),
                (
                    "reviewers_responsibilities",
                    models.TextField(
                        help_text='Newline-separated "Term: description" items'
                    ),
                ),
                (
                    "authors_responsibilities",
                    models.TextField(
                        help_text='Newline-separated "Term: description" items'
                    ),
                ),
                ("publisher_intro_text", models.TextField()),
                (
                    "publisher_roles",
                    models.TextField(help_text="Newline-separated items"),
                ),
                ("advisory_board_intro_text", models.TextField()),
                (
                    "advisory_board_responsibilities",
                    models.TextField(help_text="Newline-separated items"),
                ),
                ("human_animal_rights_text", models.TextField()),
                ("ethics_approval_text", models.TextField()),
                ("retrospective_ethics_text", models.TextField()),
                ("retrospective_studies_text", models.TextField()),
                ("case_studies_text", models.TextField()),
                (
                    "unethical_behavior_id_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
                (
                    "investigation_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
                (
                    "consequences_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
                (
                    "conflict_of_interest_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
                (
                    "appeals_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
                (
                    "corrections_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
                (
                    "retractions_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
            ],
            options={
                "verbose_name": "Ethics & Malpractice Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GuidelinesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("authors_card_description", models.TextField()),
                ("reviewers_card_description", models.TextField()),
            ],
            options={
                "verbose_name": "Guidelines Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro_title",
                    models.CharField(
                        default="An Introduction to the Journal", max_length=200
                    ),
                ),
                ("video_url", models.CharField(max_length=500)),
                ("about_title", models.CharField(max_length=200)),
                ("mission_heading", models.CharField(max_length=200)),
                ("mission_intro", models.TextField()),
                ("mission_item_1", models.TextField()),
                ("mission_item_2", models.TextField()),
                ("organogram_heading", models.CharField(max_length=200)),
                ("chief_editor_title", models.CharField(max_length=200)),
                ("chief_editor_para_1", models.TextField()),
                ("chief_editor_para_2", models.TextField()),
                ("chief_editor_para_3", models.TextField()),
                ("chief_editor_para_4", models.TextField()),
                ("chief_editor_name", models.CharField(max_length=200)),
                ("chief_editor_role", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IndexingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
                (
                    "icon",
                    models.CharField(
                        help_text="Material icon name, e.g. school", max_length=50
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=500)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Indexing Entry",
                "verbose_name_plural": "Indexing Entries",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="IndexingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("note_text", models.TextField()),
            ],
            options={
                "verbose_name": "Indexing Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JhstJournalsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
            ],
            options={
                "verbose_name": "JHST Journals Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MetricsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("impact_factor", models.CharField(max_length=20)),
                ("impact_factor_note", models.CharField(max_length=50)),
                ("avg_days_first_decision", models.CharField(max_length=10)),
                ("avg_days_to_publication", models.CharField(max_length=10)),
                ("acceptance_rate", models.CharField(max_length=10)),
                ("full_text_downloads", models.CharField(max_length=20)),
                ("abstract_views", models.CharField(max_length=20)),
                ("unique_visitors", models.CharField(max_length=20)),
                ("countries_reached", models.CharField(max_length=10)),
                ("total_citations", models.CharField(max_length=20)),
                ("h_index", models.CharField(max_length=10)),
                ("i10_index", models.CharField(max_length=10)),
                ("data_updated_note", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Metrics Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OpenAccessPolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
            ],
            options={
                "verbose_name": "Open Access Policy Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrganogramItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=2)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "color",
                    models.CharField(
                        help_text="Hex color, e.g. #00529B", max_length=10
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Organogram Item",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PeerReviewPolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("process_text", models.TextField()),
                ("desk_rejection_text", models.TextField()),
                ("guidelines_intro", models.TextField()),
                ("guidelines_note", models.TextField()),
                ("title_page_text", models.TextField()),
                ("blinded_ms_intro", models.TextField()),
                (
                    "blinded_ms_items",
                    models.TextField(help_text="Newline-separated items"),
                ),
            ],
            options={
                "verbose_name": "Peer Review Policy Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlagiarismPolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("software_text", models.TextField()),
            ],
            options={
                "verbose_name": "Plagiarism Policy Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PoliciesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_access_text", models.TextField()),
                ("copyright_text", models.TextField()),
                ("ethics_intro_text", models.TextField()),
                (
                    "ethics_items",
                    models.TextField(
                        help_text='Newline-separated bullet items (format: "Term: description")'
                    ),
                ),
                ("peer_review_intro", models.TextField()),
                (
                    "peer_review_steps",
                    models.TextField(
                        help_text='Newline-separated numbered items (format: "Term: description")'
                    ),
                ),
                ("archiving_text", models.TextField()),
            ],
            options={
                "verbose_name": "Policies Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PtiJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("issn", models.CharField(max_length=20)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "PTI Journal",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PublicationFeesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("international_label", models.CharField(max_length=100)),
                ("international_fee", models.CharField(max_length=20)),
                ("international_currency", models.CharField(max_length=10)),
                ("domestic_label", models.CharField(max_length=100)),
                ("domestic_fee", models.CharField(max_length=20)),
                ("domestic_currency", models.CharField(max_length=10)),
                ("fee_note", models.TextField()),
                ("submission_fees_text", models.TextField()),
                ("waiver_policy_text", models.TextField()),
                ("payment_methods_text", models.TextField()),
            ],
            options={
                "verbose_name": "Publication Fees Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PublicationSchedulePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("biannual_intro", models.TextField()),
                ("online_first_text", models.TextField()),
                ("special_issues_text", models.TextField()),
            ],
            options={
                "verbose_name": "Publication Schedule Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PublicationsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("schedule_frequency_text", models.TextField()),
            ],
            options={
                "verbose_name": "Publications Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReviewerGuidelinesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("confidentiality_text", models.TextField()),
                ("timeliness_text", models.TextField()),
                ("scope_quality_text", models.TextField()),
                ("review_report_intro", models.TextField()),
                (
                    "review_report_items",
                    models.TextField(
                        help_text='Newline-separated "Term: description" items'
                    ),
                ),
                ("review_report_close", models.TextField()),
                ("ethical_issues_text", models.TextField()),
                ("benefits_text", models.TextField()),
            ],
            options={
                "verbose_name": "Reviewer Guidelines Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SubscriptionAdvertisingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_text", models.TextField()),
                ("open_access_text", models.TextField()),
            ],
            options={
                "verbose_name": "Subscription & Advertising Page",
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("editor_in_chief", "Editor-in-Chief"),
                            ("managing_director", "Managing Director"),
                            ("editorial_assistant", "Editorial Assistant"),
                            ("section_editor", "Section Editor"),
                            ("editorial_board", "Editorial Board"),
                        ],
                        max_length=30,
                    ),
                ),
                ("affiliation", models.CharField(max_length=300)),
                ("bio", models.TextField()),
                ("email", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Team Member",
                "ordering": ["role_type", "order"],
            },
        ),
    ]
