# Generated by Django 4.2.1 on 2026-05-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="chief_editor_photo",
            field=models.ImageField(blank=True, upload_to="chief_editor/"),
        ),
    ]
