# Generated by Django 4.2.1 on 2026-05-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_homepage_chief_editor_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="keywords_image",
            field=models.ImageField(blank=True, upload_to="sidebar/"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="new_release_image",
            field=models.ImageField(blank=True, upload_to="sidebar/"),
        ),
    ]
