# Generated by Django 4.2.1 on 2026-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_homepage_keywords_image_homepage_new_release_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationschedulepage",
            name="issue1_description",
            field=models.CharField(default="Issue 1", max_length=100),
        ),
        migrations.AddField(
            model_name="publicationschedulepage",
            name="issue1_month",
            field=models.CharField(default="June", max_length=50),
        ),
        migrations.AddField(
            model_name="publicationschedulepage",
            name="issue2_description",
            field=models.CharField(default="Issue 2", max_length=100),
        ),
        migrations.AddField(
            model_name="publicationschedulepage",
            name="issue2_month",
            field=models.CharField(default="December", max_length=50),
        ),
    ]
