# Generated by Django 4.2.1 on 2026-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_publicationschedulepage_issue1_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialteampage",
            name="editor_in_chief_description",
            field=models.TextField(blank=True),
        ),
    ]
