# Generated by Django 4.2.1 on 2026-06-08 13:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_publicationschedulepage_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialteampage',
            name='advisory_board_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aimscopepage',
            name='scope_col1',
            field=ckeditor.fields.RichTextField(help_text='Enter bullet list content for left column'),
        ),
        migrations.AlterField(
            model_name='aimscopepage',
            name='scope_col2',
            field=ckeditor.fields.RichTextField(help_text='Enter bullet list content for right column'),
        ),
        migrations.AlterField(
            model_name='authorguidelinespage',
            name='checklist_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list for each checklist item'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='advisory_board_responsibilities',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='appeals_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='authors_responsibilities',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='conflict_of_interest_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='consequences_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='corrections_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='editors_responsibilities',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='investigation_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='publisher_roles',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='retractions_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='reviewers_responsibilities',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='ethicsmalpracticepage',
            name='unethical_behavior_id_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list'),
        ),
        migrations.AlterField(
            model_name='peerreviewpolicypage',
            name='blinded_ms_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list for each item'),
        ),
        migrations.AlterField(
            model_name='policiespage',
            name='ethics_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor bullet list for each item'),
        ),
        migrations.AlterField(
            model_name='policiespage',
            name='peer_review_steps',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor numbered list for each step'),
        ),
        migrations.AlterField(
            model_name='reviewerguidelinespage',
            name='review_report_items',
            field=ckeditor.fields.RichTextField(help_text='Use CKEditor for term: description list items'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_type',
            field=models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('managing_director', 'Managing Director'), ('editorial_assistant', 'Editorial Assistant'), ('section_editor', 'Section Editor'), ('editorial_board', 'Editorial Board'), ('advisory_board', 'Advisory Board')], max_length=30),
        ),
    ]
