# Generated by Django 4.2.1 on 2026-06-08 14:14

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_editorialteampage_advisory_board_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn_online', models.CharField(default='1595 - 431 (Online)', max_length=50)),
                ('issn_print', models.CharField(default='2025(Print)', max_length=50)),
                ('copyright_text', models.CharField(default='© 2025 Journal of Hydrocarbon Science & Technology — Petroleum Training Institute, Effurun', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
    ]
