# Generated by Django 4.2.1 on 2026-08-18 18:28

import ckeditor.fields
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_teammember_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceProceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='proceedings/covers/')),
                ('pdf_document', models.FileField(upload_to='proceedings/documents/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Conference Proceeding',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConferencesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Conferences Page',
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
    ]
