# Generated by Django 4.2.1 on 2026-09-21 19:58

import ckeditor.fields
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_conferenceproceeding_conferencespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForLibrariansPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(help_text='Information for librarians')),
            ],
            options={
                'verbose_name': 'Information for Librarians Page',
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ForReadersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(help_text='Information for readers')),
            ],
            options={
                'verbose_name': 'Information for Readers Page',
            },
            bases=(pages.models.SingletonMixin, models.Model),
        ),
    ]
