from django.urls import path
from . import views, feeds
from .forms import UserLoginForm
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='journal/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/manuscript/<int:manuscript_id>/', views.dashboard_manuscript_detail, name='dashboard_manuscript_detail'),
    path('dashboard/my-submissions/', views.my_submissions, name='my_submissions'),
    path('dashboard/my-submissions/<int:manuscript_id>/', views.my_submission_detail, name='my_submission_detail'),
    path('dashboard/review-assignment/<int:manuscript_id>/', views.reviewer_manuscript_detail, name='reviewer_manuscript_detail'),
    path('dashboard/assigned-reviews/', views.assigned_reviews, name='assigned_reviews'),
    path('profile/', views.profile, name='profile'),
    path('submit/', views.submit_manuscript, name='submit_manuscript'),
    path('assign_reviewer/<int:manuscript_id>/', views.assign_reviewer, name='assign_reviewer'),
    path('submit_review/<int:manuscript_id>/', views.submit_review, name='submit_review'),
    path('make_decision/<int:manuscript_id>/', views.make_decision, name='make_decision'),
    path('publish_article/<int:manuscript_id>/', views.publish_article, name='publish_article'),
    path('mark_as_paid/<int:manuscript_id>/', views.mark_as_paid, name='mark_as_paid'),
    path('create_issue/', views.create_issue, name='create_issue'),
    path('create_volume/', views.create_volume, name='create_volume'),
    path('manage_volumes/', views.manage_volumes, name='manage_volumes'),
    path('manage_volumes/issue/<int:issue_id>/', views.manage_issue, name='manage_issue'),
    path('issues/<int:issue_id>/', views.issue_detail, name='issue_detail'),
    path('article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('search/', views.search, name='search'),
    path('notifications/read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),

    # Static Pages (Now Dynamic CMS)
    path('about/', views.cms_page, {'slug': 'about'}, name='about'),
    path('about/aim-scope/', views.cms_page, {'slug': 'aim-scope'}, name='aim_scope'),
    path('about/editorial-team/', views.cms_page, {'slug': 'editorial-team'}, name='editorial_team'),
    path('about/publication-schedule/', views.cms_page, {'slug': 'publication-schedule'}, name='publication_schedule'),
    path('about/publication-fees/', views.cms_page, {'slug': 'publication-fees'}, name='publication_fees'),
    path('about/contact/', views.cms_page, {'slug': 'contact'}, name='contact'),
    path('publications/', views.cms_page, {'slug': 'publications'}, name='publications'),
    path('publications/current/', views.current_issue, name='current_issue'),
    path('publications/archives/', views.archives, name='archives'),
    path('indexing/', views.cms_page, {'slug': 'indexing'}, name='indexing'),

    path('metrics/', views.cms_page, {'slug': 'metrics'}, name='metrics'),
    path('guidelines/', views.cms_page, {'slug': 'guidelines'}, name='guidelines'),
    path('guidelines/author/', views.cms_page, {'slug': 'author-guidelines'}, name='author_guidelines'),
    path('guidelines/reviewer/', views.cms_page, {'slug': 'reviewer-guidelines'}, name='reviewer_guidelines'),
    path('policies/ethics/', views.cms_page, {'slug': 'ethics-malpractice'}, name='ethics_malpractice'),
    path('policies/open-access/', views.cms_page, {'slug': 'open-access-policy'}, name='open_access_policy'),
    path('policies/editorial/', views.cms_page, {'slug': 'editorial-policy'}, name='editorial_policy'),
    path('policies/peer-review/', views.cms_page, {'slug': 'peer-review-policy'}, name='peer_review_policy'),
    path('policies/archiving/', views.cms_page, {'slug': 'archiving-policy'}, name='archiving_policy'),
    path('policies/subscription/', views.cms_page, {'slug': 'subscription-advertising'}, name='subscription_advertising'),
    path('policies/plagiarism/', views.cms_page, {'slug': 'plagiarism-policy'}, name='plagiarism_policy'),
    path('policies/', views.cms_page, {'slug': 'policies'}, name='policies'),
    path('announcements/', views.announcements, name='announcements'),
    path('announcements/<int:announcement_id>/', views.announcement_detail, name='announcement_detail'),
    path('jhst-journals/', views.cms_page, {'slug': 'jhst-journals'}, name='jhst_journals'),
    path('rss/', feeds.LatestArticlesFeed(), name='article_feed'),
]
